[package]
name = "netbench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdrhistogram = "7.4.0"
libc = { version = "0.2.108", features = [ "extra_traits" ] }
pcap ="0.9.1"
